worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;

    log_format detailed '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $body_bytes_sent '
                       '"$http_referer" "$http_user_agent" '
                       'upstream: $upstream_addr '  #показывает какой сервер ответил
                       'request_time: $request_time';

    upstream backend {
        #least_conn; наим кол во подкл
        server 127.0.0.1:5004;
        server 127.0.0.1:5003;
        server 127.0.0.1:5002;
        server 127.0.0.1:5001;
    }

    # “очка входа дл€ пользователей - порт 8080
    server {
        listen 8080;
        server_name localhost;

        # ”казываем куда писать логи и какой формат использовать
        access_log logs/access.log detailed; 
        error_log logs/error.log;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}